#! /bin/bash

# Returns the command line for 'jam' associated to input filenames.

for file in "$@"; do

	N=${file:0:4}
	rho=0.${file:6:4}
	gdot=${file:13:4}
	kd=${file:20:4}
	m=${file:26:4}
	alpha=${file:33:1}.${file:34:2}
	invdt=${file:40:2}

	echo "N=${N} rho=${rho} gdot=${gdot} kd=${kd} m=${m} alpha=${alpha} invdt=${invdt}"

done
