#! /bin/sh

# Run plo scripts (Peter Olsson) on landau.tp.umu.se and copy resulting plots to yketa.

HO=${HOST-umea_lab} # computer on which to execute plo
path=/Users/yketa/Cours/ENS/M1/Stage/Umeå/simulations # directory to save data on local

if [ $# -gt 0 ]; then # plot the files in input

	for file in "$@"; do

			if [ ! -f $file ]; then # file does not exist
				echo ${file}' does not exist.'
			else # file exists

				plotname=`echo $file | sed s,^.*/,,g` # erases everything until the last /

				ssh -X $HO "/home/yketa/bin/plo" < $file # plotting

				fig=`echo $plotname | sed s/.plo/.ps/` # figure.plo > figure.ps
				scp $HO:/home/yketa/Desktop/Elli/figs/$fig ${path}/figs # get figure
					# we assume that figures are always saved to ~/Desktop/Elli/figs/

				open ${path}/figs/$fig

			fi
	done

else # plot all the files in simulations/plots

	for file in `ls ${path}/plots/ | grep .plo`; do

		ssh $HO "/home/yketa/bin/plo" < ${path}/plots/$file # plotting

		fig=`echo $file | sed s/.plo/.ps/`
		scp $HO:/home/yketa/Desktop/Elli/figs/$fig ${path}/figs # get figure
			# we assume that figures are always saved to ~/Desktop/Elli/figs/

		open ${path}/figs/$fig

	done

fi
