#! /bin/bash

# Plo script which is adapted with input parameters.

# Returns the mean and standard deviation of variable var.

var=$1 # variable which we calculate the mean and standard deviation

cat <<EOF
# calculation of the mean

cal mean 0
for value 0 ${var}.n1-1 cal mean mean+${var}[value]
cal mean mean/${var}.n1

# calculation of the standard deviation

cal stdev 0
for value 0 ${var}.n1-1 cal stdev stdev+(${var}[value]-mean)^2/${var}.n1
cal stdev sqrt(stdev)
EOF
